language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - echo "require 'sequel'; DB = Sequel.connect('postgres://postgres@127.0.0.1:5432/stld_test')" > config/connection.rb
  - psql -c 'create database stld_test;' -U postgres
  - bundle exec sequel -M 0 -m migrations -E postgres://postgres@127.0.0.1:5432/stld_test
  - bundle exec sequel -m migrations -E postgres://postgres@127.0.0.1:5432/stld_test

script: ruby ./script/test.rb
