language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database stld_test;' -U postgres
  - bundle exec ruby script/recreate_db.rb

script: bundle exec ruby ./script/test.rb
