language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_install:
  - npm install coffee-script
before_script:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database stld_test;' -U postgres
  - RACK_ENV=test bundle exec ruby script/migrate.rb destroy
  - RACK_ENV=test bundle exec ruby script/migrate.rb
  - script/compile_js.sh

script:
  - bundle exec ruby ./script/test.rb
  - bundle exec ruby ./script/test.rb features
